#ifndef WIN32_VERSION_H
#define WIN32_VERSION_H

// TODO: make this autogenerated

#define VER_FILEVERSION             0,1,0,0
#define VER_FILEVERSION_STR         "0.1.0.0\0"

#define VER_PRODUCTVERSION          0,1,0,0
#define VER_PRODUCTVERSION_STR      "0.1\0"

#define VER_COMPANYNAME_STR         "GPLv3"
#define VER_FILEDESCRIPTION_STR     "EVE Online character monitor"
#define VER_ORIGINALFILENAME_STR    "qmlevemon"
#define VER_INTERNALNAME_STR        VER_ORIGINALFILENAME_STR
#define VER_LEGALCOPYRIGHT_STR      VER_COMPANYNAME_STR
#define VER_PRODUCTNAME_STR         "QMLEVEMon"

#endif // WIN32_VERSION_H
